name: Update Article Lists
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Manifest Generator
        run: python generate_list.py
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add articles/*/list.json
          git commit -m "Auto-update article manifests" || exit 0
          git push
